version: 3.0.{build}
image: Visual Studio 2017

test: off

install:
  - ps: $env:DOTNET_BUILD_VERSION = $env:APPVEYOR_BUILD_NUMBER

build_script:
  - cmd: build.sh

artifacts:
  - path: artifacts\*.nupkg
